Update concepts.md
life-itself/diginomics pull request #67
Opened 2023-04-14 14:00 UTC by theo-cox

[m]: updated with revised building blocks

2023-04-17 02:01 UTC, rufuspollock commented
@theo-cox is there a reason this isn't merged? If you want my review put me as a reviewer and @ me ...

2023-04-17 02:14 UTC, rufuspollock requested changes
Made some suggestions for improvements. Can obviously merge as is and then make the changes or make the changes directly and then merge.

2023-04-17 02:14 UTC, rufuspollock commented on content/notes/concepts.md
> +**Digital goods **are all those economic goods which are made up of data or information. These can range from software to datasets to music and even pieces of intellectual property such as pharmaceut
That is a formatting bug

2023-04-17 02:14 UTC, rufuspollock commented on content/notes/concepts.md
> +Business models are composed of **building blocks** which can be assembled under **constraints **to make a **limited number of business model types**. Learning these types–and the list of blocks and
@theo-cox formatting bug ... should be 

```
**constraints** ...
```

2023-04-17 02:14 UTC, rufuspollock commented on content/notes/concepts.md
> +* **Revenue model** - how you earn revenue
Nice ... much clearer

2023-04-17 02:14 UTC, rufuspollock commented on content/notes/concepts.md
>  * **Level of access** - how widely accessible the business model makes data
Minor style point: usually you'd have `:` here no `-` e.g.

```
**Level of access**: how widely accessible the business model makes data
```

2023-04-17 02:14 UTC, rufuspollock commented on content/notes/concepts.md
> +![building blocks](https://user-images.githubusercontent.com/72795023/232063665-80cbe3c0-5a21-42e4-95d5-e59258f869eb.svg)
It would be preferable to put svg in the repo - but we can fix this later.

2023-04-17 02:14 UTC, rufuspollock commented on content/notes/concepts.md
> +* **Grants/Subsidies** - revenue comes exclusively from grants or subsidies, usually from public bodies or philanthropists but also possible other sources such as sector associations. These can be **
Italics and bold is probably not needed for conditional and unconditional

2023-04-17 02:14 UTC, rufuspollock commented on content/notes/concepts.md
Lot of white space here ...

2023-04-17 02:14 UTC, rufuspollock commented on content/notes/concepts.md
> +* You cannot have a fully Open access business model and have user fees of any kind.
Strictly, you could with dual licensing so maybe phrase as ...

```
A fully open access business model by definition means that user fees must be zero, at least for direct access 
```

2023-04-17 02:14 UTC, rufuspollock commented on content/notes/concepts.md
>  * **Access**: optimizing for social welfare will mean selecting a business model which prioritizes high levels of access. By contrast, business models which use closed rights frameworks may enable yo
"you" here should be clarified e.g.

... may enable the *database provider* to make more money

2023-04-17 02:14 UTC, rufuspollock commented on content/notes/concepts.md
> +* **Quality**: optimizing for social welfare will mean setting the level of data quality at the most useful level affordable, all things being equal. By contrast, a business model seeking to make the
Maybe, for fairness add a comment lkie ...

Obviously, business models that generate little revenue will  struggle to maintain quality.

2023-04-17 02:14 UTC, rufuspollock commented on content/notes/concepts.md
>  * **Profitability**: different models will be differently profitable. Crucially, profitability can often seem to come into conflict with access. Optimizing for money making via profit may mean the us
Not just unprofitable but may lack revenue ...

Strictly, from a social welfare point of view profitability isn't really a feature at all ... you'd only have access and quality ... (i wonder therefore if we drop profitability for now ...?)

2023-04-17 02:14 UTC, rufuspollock commented on content/notes/concepts.md
>  Different model types will have different **features.** These are specific characteristics of how the business model functions. The major features we will consider are:
0️⃣ formatting in that fullstop should be outside the bold.

2023-04-17 02:14 UTC, rufuspollock commented on content/notes/concepts.md
>  The diagram below shows the different options available for each building block. We will describe these below. Note that even these options are themselves broad umbrellas and can themselves branch in
broad umbrellas => broad categories

Could tweak that second sentence to something like:

Note that these options are categories and each one can be varied and tweaked in a variety of ways. Our aim here is to give a broad outline and distinguish the main categories from which one begins to assemble a business model. Think of it like a car: you choose the make and model and the broad features and then at the end you choose details like the specific color or trim or whether it has a sunroof or not.

2023-04-19 07:16 UTC, merged

2023-04-19 09:46 UTC, theo-cox commented
@rufuspollock all suggestions now merged