Create new-site.md
life-itself/diginomics pull request #75
Opened 2023-04-27 08:45 UTC by theo-cox

[m]: create blog for SCQA about site transition

2023-04-27 08:46 UTC, theo-cox commented
@rufuspollock SCQA blog here

2023-04-28 10:08 UTC, rufuspollock requested changes
This was already good. Changes are relatively minor - they are about "making it read" better and some refinement of intent and tone.

I've left detailed comments for your edification (haven't quite finished - and think easy to edit directly now).

For now i'm going to copy your text, apply changes and commit - and you can see the relative changes if you wish.

2023-04-28 10:08 UTC, rufuspollock commented on content/notes/new-site.md
> +# Situation
`## Context: Open Revolution is five years old and much has changed`

2023-04-28 10:08 UTC, rufuspollock commented on content/notes/new-site.md
> +# Complication
`## The Need and Opportunity: there's a broader topic to address and we already have the material`

2023-04-28 10:08 UTC, rufuspollock commented on content/notes/new-site.md
> +# Question
`## How can we evolve this project?

2023-04-28 10:08 UTC, rufuspollock commented on content/notes/new-site.md
> +What do we build which incorporates our existing work and thinking in a way which makes it accessible and useful for diverse people and challenges, and which does not require the use of significant e
How can we evolve this project?  ...

2023-04-28 14:07 UTC, closed without merging